// Package brew generates and publishes Homebrew formulas.
//
// The formula installs the archives this release produced, with the digests
// the manifest recorded, from URLs on the release letsgo just published. That
// is the whole reason to generate it here rather than by hand: the digests
// have to come from the build, and a formula written against GitHub's
// automatically generated source tarball is pinned to bytes nobody controls.
//
// Rendering is deterministic, which makes publication idempotent: an unchanged
// formula produces an identical file, and an identical file is not committed
// again. Re-running a release does not churn the tap.
package brew

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
	"text/template"
	"unicode"
)

// Platform is one prebuilt archive the formula can install.
type Platform struct {
	OS     string
	Arch   string
	URL    string
	SHA256 string
}

// Formula describes one binary to publish.
type Formula struct {
	// Binary is the executable's name, which is also the formula's name.
	Binary string

	Version  string
	Homepage string

	// Description and License are optional; a formula without them is valid,
	// and inventing either would be worse than omitting it.
	Description string
	License     string

	Platforms []Platform
}

// supported lists the platform pairs Homebrew itself supports. Anything else
// letsgo builds — and it builds Windows — has no place in a formula.
var supported = map[string]bool{
	"darwin/amd64": true,
	"darwin/arm64": true,
	"linux/amd64":  true,
	"linux/arm64":  true,
}

// FileName is where the formula belongs in a tap.
func (f Formula) FileName() string { return "Formula/" + f.Binary + ".rb" }

// ClassName is the Ruby class Homebrew expects, derived from the binary name
// the way Homebrew's own `brew create` derives it.
func (f Formula) ClassName() string {
	var b strings.Builder
	upper := true
	for _, r := range f.Binary {
		switch {
		case r == '-' || r == '_' || r == '.' || r == '+':
			upper = true
		case upper:
			b.WriteRune(unicode.ToUpper(r))
			upper = false
		default:
			b.WriteRune(r)
		}
	}
	return b.String()
}

// Render produces the formula.
func (f Formula) Render() ([]byte, error) {
	if f.Binary == "" || f.Version == "" || f.Homepage == "" {
		return nil, fmt.Errorf("brew: binary, version and homepage are required")
	}

	usable := make([]Platform, 0, len(f.Platforms))
	for _, p := range f.Platforms {
		if supported[p.OS+"/"+p.Arch] {
			usable = append(usable, p)
		}
	}
	if len(usable) == 0 {
		return nil, fmt.Errorf("brew: %s has no macOS or Linux build to install", f.Binary)
	}
	// Sorted so that the same release always renders the same bytes, which is
	// what lets publication skip an unchanged formula.
	sort.Slice(usable, func(i, j int) bool {
		if usable[i].OS != usable[j].OS {
			return usable[i].OS < usable[j].OS
		}
		return usable[i].Arch < usable[j].Arch
	})

	data := struct {
		Formula
		Class string
		MacOS []Platform
		Linux []Platform
	}{Formula: f, Class: f.ClassName()}

	for _, p := range usable {
		if p.OS == "darwin" {
			data.MacOS = append(data.MacOS, p)
			continue
		}
		data.Linux = append(data.Linux, p)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("brew: rendering %s: %w", f.FileName(), err)
	}
	return buf.Bytes(), nil
}

// quote renders a Ruby double-quoted string. Only the two characters that can
// end or escape one need handling; a description containing either is rare and
// silently producing invalid Ruby is not an acceptable way to handle it.
func quote(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`)
	return `"` + r.Replace(s) + `"`
}

func archBlock(p Platform) string {
	if p.Arch == "arm64" {
		return "on_arm"
	}
	return "on_intel"
}

var tmpl = template.Must(template.New("formula").Funcs(template.FuncMap{
	"quote": quote,
	"arch":  archBlock,
}).Parse(`# Generated by letsgo. Do not edit; the next release will overwrite it.
class {{.Class}} < Formula
{{- with .Description}}
  desc {{quote .}}
{{- end}}
  homepage {{quote .Homepage}}
  version {{quote .Version}}
{{- with .License}}
  license {{quote .}}
{{- end}}
{{if .MacOS}}
  on_macos do
{{- range .MacOS}}
    {{arch .}} do
      url {{quote .URL}}
      sha256 {{quote .SHA256}}
    end
{{- end}}
  end
{{end}}{{if .Linux}}
  on_linux do
{{- range .Linux}}
    {{arch .}} do
      url {{quote .URL}}
      sha256 {{quote .SHA256}}
    end
{{- end}}
  end
{{end}}
  def install
    bin.install {{quote .Binary}}
  end

  test do
    # letsgo verifies before publishing that the binary reports this version,
    # so asserting it here catches a formula pointing at the wrong release
    # rather than merely proving the binary starts.
    assert_match {{quote .Version}}, shell_output("#{bin}/{{.Binary}} --version")
  end
end
`))
