// Package install generates a self-verifying installer for a release.
//
// The script is pinned to the release that produced it and carries every
// archive's digest inline, so installing needs no checksum file, no manifest,
// no forge API and no JSON parser — and, more to the point, no trust in
// anything fetched alongside the archive. A tampered SHA256SUMS cannot help an
// attacker here, because the script never reads one.
//
// That is the whole argument for generating it rather than writing it once by
// hand: the digests have to come from the build that just happened.
package install

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
	"text/template"
)

// FileName is the installer's published name.
const FileName = "install.sh"

// Target is one downloadable archive.
type Target struct {
	OS      string
	Arch    string
	Archive string
	SHA256  string
}

// Options describe the release to install.
type Options struct {
	Project string
	Version string

	// BaseURL is the directory the archives are published under, without a
	// trailing slash.
	BaseURL string

	Targets []Target
}

// Script renders the installer.
//
// Windows targets are left out: a POSIX shell script cannot sensibly install
// them, and listing a target the script would refuse is worse than not
// offering it.
func Script(o Options) ([]byte, error) {
	if o.Project == "" || o.Version == "" || o.BaseURL == "" {
		return nil, fmt.Errorf("install: project, version and base URL are required")
	}

	targets := make([]Target, 0, len(o.Targets))
	for _, t := range o.Targets {
		if t.OS == "windows" {
			continue
		}
		targets = append(targets, t)
	}
	if len(targets) == 0 {
		return nil, fmt.Errorf("install: no targets a shell script can install")
	}
	sort.Slice(targets, func(i, j int) bool {
		if targets[i].OS != targets[j].OS {
			return targets[i].OS < targets[j].OS
		}
		if targets[i].Arch != targets[j].Arch {
			return targets[i].Arch < targets[j].Arch
		}
		return targets[i].Archive < targets[j].Archive
	})

	o.Targets = targets
	o.BaseURL = strings.TrimSuffix(o.BaseURL, "/")

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, o); err != nil {
		return nil, fmt.Errorf("install: rendering %s: %w", FileName, err)
	}
	return buf.Bytes(), nil
}

// Platforms lists the os/arch pairs the script supports, for reporting.
func Platforms(targets []Target) []string {
	seen := map[string]bool{}
	var out []string
	for _, t := range targets {
		if t.OS == "windows" || seen[t.OS+"/"+t.Arch] {
			continue
		}
		seen[t.OS+"/"+t.Arch] = true
		out = append(out, t.OS+"/"+t.Arch)
	}
	sort.Strings(out)
	return out
}

// tmpl is the installer. It is POSIX sh rather than bash: the smallest
// container images ship ash or dash, and an installer that needs a shell
// installed first is not an installer.
var tmpl = template.Must(template.New("install.sh").Parse(`#!/bin/sh
# Installer for {{.Project}} {{.Version}}, generated by letsgo.
#
# Every digest below was recorded by the build that produced these archives.
# Nothing downloaded by this script is trusted before it has been checked
# against them, so a compromised release page cannot substitute an archive.
#
# usage: install.sh [-b <dir>]
#   -b   where to put the binaries (default: ./bin, or $BINDIR)

set -eu

PROJECT='{{.Project}}'
VERSION='{{.Version}}'
BASE='{{.BaseURL}}'

# os arch archive sha256
ARCHIVES='{{range .Targets}}
{{.OS}} {{.Arch}} {{.Archive}} {{.SHA256}}{{end}}'

usage() {
	echo "usage: install.sh [-b <dir>]"
	echo "  installs $PROJECT $VERSION, verifying each archive against a recorded digest"
	echo "  -b   where to put the binaries (default: ./bin, or \$BINDIR)"
}

BINDIR="${BINDIR:-./bin}"
while getopts 'b:h' opt; do
	case "$opt" in
		b) BINDIR="$OPTARG" ;;
		h) usage; exit 0 ;;
		*) usage >&2; exit 2 ;;
	esac
done

fail() { echo "install: $*" >&2; exit 1; }

os=$(uname -s | tr '[:upper:]' '[:lower:]')
case "$os" in
	linux|darwin) ;;
	*) fail "$os is not supported by this installer" ;;
esac

arch=$(uname -m)
case "$arch" in
	x86_64|amd64) arch=amd64 ;;
	aarch64|arm64) arch=arm64 ;;
	*) fail "$arch is not supported by this installer" ;;
esac

matches=$(echo "$ARCHIVES" | awk -v os="$os" -v arch="$arch" '$1 == os && $2 == arch { print $3, $4 }')
[ -n "$matches" ] || fail "$PROJECT $VERSION has no build for $os/$arch"

# Downloading with whichever of the two is present, rather than requiring one,
# is the difference between working on a bare container and not.
if command -v curl >/dev/null 2>&1; then
	fetch() { curl -fsSL "$1" -o "$2"; }
elif command -v wget >/dev/null 2>&1; then
	fetch() { wget -qO "$2" "$1"; }
else
	fail 'neither curl nor wget is installed'
fi

# GNU coreutils and macOS disagree on the name and on the output format, so
# both are normalised to a bare digest here rather than at each call site.
if command -v sha256sum >/dev/null 2>&1; then
	digest() { sha256sum "$1" | cut -d' ' -f1; }
elif command -v shasum >/dev/null 2>&1; then
	digest() { shasum -a 256 "$1" | cut -d' ' -f1; }
else
	fail 'neither sha256sum nor shasum is installed, so nothing could be verified'
fi

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT INT TERM
mkdir -p "$tmp/unpacked"

# Read from a file rather than a pipe: a pipeline runs the loop in a subshell,
# where a failed verification would exit that subshell and not this script.
echo "$matches" > "$tmp/matches"

while read -r archive want; do
	echo "install: downloading $archive"
	fetch "$BASE/$archive" "$tmp/$archive" || fail "could not download $archive"

	got=$(digest "$tmp/$archive")
	if [ "$got" != "$want" ]; then
		fail "$archive does not match its recorded digest
  expected $want
  got      $got"
	fi

	tar -xzf "$tmp/$archive" -C "$tmp/unpacked" || fail "could not extract $archive"
done < "$tmp/matches"

mkdir -p "$BINDIR"

# The archives hold the binary at the top level alongside documentation, so
# anything executable that is not a directory is a binary to install.
installed=0
for file in "$tmp"/unpacked/*; do
	[ -f "$file" ] && [ -x "$file" ] || continue
	name=$(basename "$file")
	mv "$file" "$BINDIR/$name"
	chmod +x "$BINDIR/$name"
	echo "install: $BINDIR/$name"
	installed=$((installed + 1))
done
[ "$installed" -gt 0 ] || fail 'the archive contained no executable'

echo "install: $PROJECT $VERSION installed to $BINDIR"
`))
